# Generated by Django 4.1.3 on 2022-11-28 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='multi_choice',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('answer', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('date', models.CharField(max_length=10)),
                ('explanation', models.TextField()),
            ],
        ),
    ]
